from __future__ import annotations

SYNONYMS: dict[str, list[str]] = {
    "commute": [
        "commute",
        "commuting",
        "distance",
        "km",
        "pendeln",
        "pendler",
        "pendlerpauschale",
        "entfernungspauschale",
        "fahrtkosten",
        "weg zur arbeit",
    ],
    "home_office": [
        "home office",
        "home-office",
        "remote",
        "work from home",
        "wfh",
        "homeoffice",
        "homeoffice pauschale",
        "arbeitszimmer pauschale",
    ],
    "equipment": [
        "equipment",
        "tools",
        "work equipment",
        "laptop",
        "computer",
        "monitor",
        "chair",
        "desk",
        "drucker",
        "arbeitsmittel",
        "beruflich",
    ],
    "donations": [
        "donation",
        "donations",
        "charity",
        "spende",
        "spenden",
        "gemeinnützig",
        "sonderausgaben",
        "verein",
    ],
}
